version: '2'

networks:
  prodnetwork:
    driver: bridge
services:
  postgres:
      image: postgres:9.6
      ports:
        - "5432:5432"
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: santa_db
