spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/santa_db
    username: postgres
    password: postgres
    platform: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
  profiles:
    active: local
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
santa:
  url: http://localhost:8083